keytracker/routes/ui.py
from flask_login import (
    login_required,
    logout_user,
    current_user,
)
from flask import (
    Blueprint,
    flash,
    render_template,
    redirect,
    request,
    send_from_directory,
    send_file,
    url_for,
)
from keytracker.schema import (
    CardInDeck,
    db,
    Deck,
    Game,
    Log,
    Player,
)
from keytracker.utils import (
    add_player_filters,
    add_game_sort,
    anonymize_game_for_player,
    BadLog,
    basic_stats_to_game,
    DeckNotFoundError,
    get_deck_by_id_with_zeal,
    house_stats_to_csv,
    log_to_game,
    parse_house_stats,
    turn_counts_from_logs,
)
from sqlalchemy import and_, or_
from sqlalchemy.orm import joinedload
import datetime
import time
import logging
import os


blueprint = Blueprint("ui", __name__, template_folder="templates")
logger = logging.getLogger(__name__)


@blueprint.route("/")
def home():
    """Landing page."""
    last_five_games = Game.query.order_by(Game.date.desc()).limit(5).all()
    return render_template(
        "home.html",
        title="Bear Tracks",
        description="KeyForge Game Records and Analysis",
        games=last_five_games,
    )


@blueprint.route("/privacy")
def privacy():
    """Privacy policy."""
    return render_template(
        "privacy.html",
        title="Privacy Policy",
        description="Bear Tracks Privacy Policy",
    )


@blueprint.route("/fame")
def hall_of_fame():
    """Hall of fame"""
    return render_template(
        "coming_soon.html",
        title="Hall of Fame",
        description="",
    )


@blueprint.route("/leaderboard")
def leaderboard():
    """Leaderboard"""
    return render_template(
        "coming_soon.html",
        title="Leaderboard",
        description="",
    )


@blueprint.route("/deck/<deck_id>", methods=["GET"])
def deck(deck_id):
    username = request.args.get("username")
    deck = get_deck_by_id_with_zeal(deck_id)
    if username is not None:
        games_won = Game.query.filter(
            and_(
                Game.winner_deck_dbid == deck.id,
                Game.winner == username,
            )
        ).count()
        games_lost = Game.query.filter(
            and_(
                Game.loser_deck_dbid == deck.id,
                Game.loser == username,
            )
        ).count()
        deck_games = (
            add_player_filters(Game.query, username, deck_dbid=deck.id)
            .order_by(Game.date.desc())
            .all()
        )
    else:
        games_won = Game.query.filter_by(winner_deck_dbid=deck.id).count()
        games_lost = Game.query.filter_by(loser_deck_dbid=deck.id).count()
        deck_games = (
            add_player_filters(Game.query, deck_dbid=deck.id)
            .order_by(Game.date.desc())
            .all()
        )
    if len(deck_games) == 0:
        flash(f"No games found for deck {deck_id}")
        return redirect(url_for("ui.home"))
    return render_template(
        "deck.html",
        title=f"{deck.name} Deck Summary",
        games=deck_games,
        deck_name=deck.name,
        deck_id=deck.kf_id,
        games_won=games_won,
        games_lost=games_lost,
    )


@blueprint.route("/game/<crucible_game_id>", methods=["GET"])
def game(crucible_game_id):
    game = Game.query.filter_by(crucible_game_id=crucible_game_id).first()
    if game is None:
        return render_template(
            "game_missing.html",
            crucible_game_id=crucible_game_id,
        )
    players = sorted(
        [game.winner, game.loser],
        key=lambda x: x != game.insist_first_player,
    )
    return render_template(
        "game.html",
        title=" vs ".join(players),
        game=game,
    )


@blueprint.route("/games", methods=["GET"])
def games():
    args_list = ["user", "deck", "sas_min", "sas_max", "aerc_min", "aerc_max"]
    if any(
        (
            request.args.get("user1"),
            request.args.get("deck1"),
        )
    ):
        query = Game.query
        query = add_player_filters(
            query, *map(request.args.get, [f"{x}1" for x in args_list])
        )
        query = add_player_filters(
            query, *map(request.args.get, [f"{x}2" for x in args_list])
        )
        query = add_game_sort(
            query, [(request.args.get("sort1"), request.args.get("direction1"))]
        )
        games = query.limit(10).all()
    else:
        games = None
    return render_template(
        "games.html",
        title=f"Games Search",
        args=request.args,
        games=games,
        sort_options={
            "date": "Date",
            "loser_keys": "Keys forged by loser",
            "combined_sas_rating": "Total SAS",
            "winner_sas_rating": "Winner SAS",
            "loser_sas_rating": "Loser SAS",
            "combined_aerc_score": "Total AERC",
            "winner_aerc_score": "Winner AERC",
            "loser_aerc_score": "Loser AERC",
        },
    )


@blueprint.route("/decks", methods=["GET"])
def decks():
    if request.args:
        query = Deck.query
        sas_min = request.args.get("sas_min")
        if sas_min:
            query = query.filter(Deck.sas_rating >= sas_min)
        sas_max = request.args.get("sas_max")
        if sas_max:
            query = query.filter(Deck.sas_rating <= sas_max)
        aerc_min = request.args.get("aerc_min")
        if aerc_min:
            query = query.filter(Deck.aerc_score >= aerc_min)
        aerc_max = request.args.get("aerc_max")
        if aerc_max:
            query = query.filter(Deck.aerc_score <= aerc_max)
        decks = query.all()
    else:
        decks = None
    return render_template(
        "decks.html",
        title=f"Decks Search",
        args=request.args,
        decks=decks,
    )


@blueprint.route("/csv_to_pods", methods=["GET"])
def csv_to_pods():
    """CSV to Pod Stats Page"""
    return render_template(
        "csv_to_pods_landing.html",
        title="Pod Stats From CSV",
    )


@blueprint.route("/csv_to_pods", methods=["POST"])
def csv_to_pods_post():
    max_decks = 1000
    max_to_fetch = 2
    decks_csv = request.files["decks_csv"]
    result_type = request.form["result_type"]
    show_card_images = bool(request.form.get("show_card_images"))
    hide_set = bool(request.form.get("hide_set"))
    house_stats = parse_house_stats(decks_csv, max_decks=max_decks)
    if result_type == "csv":
        output_csv = house_stats_to_csv(house_stats)
        output_filename = decks_csv.filename.replace(".csv", "_pod_stats.csv")
        return send_file(
            output_csv,
            download_name=output_filename,
            as_attachment=True,
        )
        response = make_response(output_csv)
        response.headers["Content-Disposition"] = "attachment; filename=pod_stats.csv"
        return response
    else:
        kf_ids = {pod.link.split("/")[-1] for pod in house_stats}
        decks = Deck.query.options(
            joinedload(Deck.cards_from_assoc).joinedload(CardInDeck.card_in_set)
        ).filter(Deck.kf_id.in_(kf_ids))
        missing_deck_count = len(kf_ids) - decks.count()
        name_to_deck = {deck.name: deck for deck in decks}
        if missing_deck_count > 0:
            missing_kf_ids = kf_ids - {d.kf_id for d in decks}
            if missing_deck_count <= max_to_fetch:
                logger.debug("Missing one or two decks, attempting to fetch.")
                for kf_id in missing_kf_ids:
                    deck = get_deck_by_id_with_zeal(kf_id)
                    name_to_deck[deck.name] = deck
            else:
                logger.debug("Missing too many decks from db, skipping some.")
                flash(
                    f"Warning: {missing_deck_count} unrecognized decks in csv. Skipping them for now, but if you try again later they may be available."
                )
                house_stats = [p for p in house_stats if p.name in name_to_deck.keys()]
        return render_template(
            "csv_to_pods.html",
            house_stats=house_stats,
            max_decks=max_decks,
            name_to_deck=name_to_deck,
            show_card_images=show_card_images,
            hide_set=hide_set,
        )


@blueprint.route("/user", methods=["GET"])
def user_search():
    """User Search Page"""
    return render_template(
        "user_search.html",
        title="User Search",
    )


@blueprint.route("/user", methods=["POST"])
def user_search_post():
    """User Search Page"""
    return redirect(url_for("ui.user", username=request.form["username"]))


@blueprint.route("/user/<username>", methods=["GET"])
def user(username):
    """User Summary Page"""
    games_won = Game.query.filter(Game.winner == username).count()
    games_lost = Game.query.filter(Game.loser == username).count()
    user_games = (
        Game.query.filter((Game.winner == username) | (Game.loser == username))
        .order_by(Game.date.desc())
        .limit(10000)
        .all()
    )
    if len(user_games) == 0:
        flash(f"No games found for user {username}")
        return redirect(url_for("ui.user_search"))
    return render_template(
        "user.html",
        title=f"{username} games",
        username=username,
        games=user_games,
        games_won=games_won,
        games_lost=games_lost,
    )


@blueprint.route("/upload", methods=["GET"])
def upload():
    return render_template(
        "upload.html",
        title="Upload a Game!",
    )


@blueprint.route("/upload", methods=["POST"])
def upload_post():
    """Manual game upload page"""
    game_start = datetime.datetime.now()
    log_text = request.form["log"]
    try:
        game = log_to_game(log_text)
    except (BadLog, DeckNotFoundError) as exc:
        flash(str(exc))
    else:
        game.date = game_start
        db.session.add(game)
        db.session.commit()
        db.session.refresh(game)
        game.crucible_game_id = f"UNKNOWN-{game.id}"
        db.session.commit()
        for seq, log in enumerate(log_text.split("\n")):

keytracker/templates/csv_to_pods.html
{% extends "layout.html" %}
{% block content %}
    <div class="pod_stats_header">
        <h1>My Pod Stats</h1>
        <p>Deck data loaded from the csv you passed in. Limited to {{ max_decks }} decks.</p>
    </div>
    <div class="house_stats">
        <table>
            <tr>
                <th>Sas</th>
                {% if not hide_set %}<th>Expansion</th>{% endif %}
                <th>House</th>
                <th>Deck</th>
                <th>Cards</th>
                <th>On Market</th>
                <th>Price</th>
            </tr>
            {% for pod in house_stats %}
                <tr>
                    <td>{{ pod.sas|round(1) }}</td>
                    {% if not hide_set %}<td>{{ pod.expansion }}</td>{% endif %}
                    <td>{{ pod.house }}</td>
                    <td>
                        <a href={{ pod.link }}>{{ pod.name }}</a>
                    </td>
                    {% if show_card_images %}
                        <td>{{ render_card_images(name_to_deck[pod.name], pod.house) | safe }}</td>
                    {% else %}
                        <td>{{ render_card_list(name_to_deck[pod.name], pod.house) | safe }}</td>
                    {% endif %}
                    <td>{{ pod.on_market }}</td>
                    <td>{{ pod.price }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

keytracker/templates/csv_to_pods_landing.html
{% extends "layout.html" %}
{% block content %}
    <h1>Get your Pod stats</h1>
    <form method="post" enctype="multipart/form-data">
        <label for="decks_csv">Upload your CSV file from DoK. Max file size is 16 MB.</label>
        <br>
        <input type="file" name="decks_csv" accept=".csv" />
        <br>
        <label for="result_type">How to get results</label>
        <br>
        <input type="radio" id="csv" name="result_type" value="csv">
        <label for="csv">CSV</label>
        <br>
        <input type="radio" id="browser" name="result_type" value="browser" checked>
        <label for="browser">In Browser</label>
        <br>
        <p>Browser Mode Options</p>
        <input type="checkbox"
               id="show_card_images"
               name="show_card_images"
               value="True">
        <label for="show_card_images">Show cards as images</label>
        <br>
        <input type="checkbox"
            id="hide_set"
            name="hide_set"
            value=True">
            <label for="hide_set">Hide Expansion</label>
            <br>
            <br>
            <button type="submit">Submit</button>
        </form>
        <h2>How do I get this "CSV" thingy?</h2>
        <ol>
            <li>
                Got to <a href="https://decksofkeyforge.com/decks">DoK</a>.
            </li>
            <li>
                Search whatever parameters you want. I like to grab all my decks of a
                particular set.
                <br>
                <img src="/static/imgs/my_aoa.png">
            </li>
            <li>
                Click
                <img src="/static/imgs/search.png">
                .
            </li>
            <li>
                Click the little download button.
                <br>
                <img src="/static/imgs/download_button.png">
            </li>
            <li>Download the CSV.</li>
            <li>Use it here.</li>
        </ol>
    {% endblock %}

keytracker/templates/deck.html
{% extends "layout.html" %}
{% block content %}
    <div class="deck_header">
        <h1>Record of games played with {{ deck_name }}</h1>
        <div class="mv_link">
            <a href="https://www.keyforgegame.com/deck-details/{{ deck_id }}">Master Vault</a>
        </div>
        <div class="dok_link">
            <a href="https://decksofkeyforge.com/decks/{{ deck_id }}">Decks of KeyForge</a>
        </div>
        <div class="games_summary">
            Total games played: {{ games_won + games_lost }} | Games won: {{ games_won }}
            ( {{ '%0.2f' | format(games_won / ( games_won + games_lost) * 100) }}% )
        </div>
        <form method="get">
            <label for="username">Limit to User:</label>
            <input type="text" name="username" placeholder="" />
            <button type="submit">Filter</button>
        </form>
    </div>
    <div class="games_list">
        {% for game in games %}{{ render_game_listing(game, username=username, deck_id=deck_id) | safe }}{% endfor %}
    </div>
{% endblock %}

keytracker/templates/decks.html
{% extends "layout.html" %}
{% block content %}
    <div class="decks_header">
        <h1>
            Decks Advanced Search
            <h1>
            </div>
            <form id="cleanform" method="get">
                {{ render_input_number("sas_min", "SAS Minimum", 33, 108, args.get("sas_min") ) | safe }}
                {{ render_input_number("sas_max", "SAS Maximum", 33, 108, args.get("sas_max") ) | safe }}
                {{ render_input_number("aerc_min", "AERC Minimum", 33, 108, args.get("aerc_min") ) | safe }}
                {{ render_input_number("aerc_max", "AERC Maximum", 33, 108, args.get("aerc_max") ) | safe }}
                <br />
                <button type="submit">Submit</button>
            </form>
            <script type="text/javascript"
                    src="{{ url_for("static", filename="js/cleanform.js") }}"></script>
            {% if decks %}
                <div class="decks_list">
                    {% for deck in decks %}
                        <div class="deck_listing">
                            <a href="{{ url_for("ui.deck", deck_id=deck.kf_id) }}">{{ deck.name }}</a>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endblock %}

keytracker/templates/game.html
{% extends "layout.html" %}
{% block content %}
    <div class="game_header">
        <h1>{{ game.winner }} versus {{ game.loser }}</h1>
        <p>{{ description }}</p>
        <p>Keys: {{ game.winner_keys }} - {{ game.loser_keys }}</p>
        <p>
            <a href="https://decksofkeyforge.com/compare-decks?decks={{ game.winner_deck.kf_id }}&decks={{ game.loser_deck.kf_id }}">Compare decks on DoK</a>
        </p>
    </div>
    <div class="game_player_summary">
        <h2>
            <a href="{{ url_for('ui.user', username=game.winner) }}">{{ game.winner }}</a> using <a href="{{ url_for('ui.deck', deck_id=game.winner_deck.kf_id) }}">{{ game.winner_deck.name }}</a>  <a game.
     href="https://keyforgegame.com/deck-details/{{ game.winner_deck.kf_id }}">MV</a>
            <a href="https://decksofkeyforge.com/decks/{{ game.winner_deck.kf_id }}">DOK</a>
        </h2>
        <h2>
            <a href="{{ url_for('ui.user', username=game.loser) }}">{{ game.loser }}</a> using <a href="{{ url_for('ui.deck', deck_id=game.loser_deck.kf_id) }}">{{ game.loser_deck.name }}</a>  <a game.
     href="https://keyforgegame.com/deck-details/{{ game.loser_deck.kf_id }}">MV</a>
            <a href="https://decksofkeyforge.com/decks/{{ game.loser_deck.kf_id }}">DOK</a>
        </h2>
    </div>
    <div class="visibility_checkbox">
        Show system messages:
        <input type="checkbox" id="show_system_messages">
    </div>
    <div class="logs">
        {% for log in game.logs %}{{ render_log(log) | safe }}{% endfor %}
    </div>
    <script type="text/javascript">
        $('.system_message').hide();
        $('#show_system_messages').click(function() {
            $('.system_message').toggle();
        })
    </script>
{% endblock %}

keytracker/templates/game_missing.html
{% extends "layout.html" %}
{% block content %}
    <p>Oops! I can't find that game.</p>
    <p>If you just uploaded, please wait a bit, then retry.</p>
    <p>
        <a href="{{ url_for(request.endpoint, **request.view_args) }}">Retry</a>
    </p>
{% endblock %}

keytracker/templates/games.html
{% extends "layout.html" %}
{% block content %}
    <div class="games_header">
        <h1>Games Advanced Search</h1>
        <div class="games_summary">Games Search</div>
    </div>
    <form id="cleanform" method="get">
        <div class="player_filter_inputs">
            <p class="form_element">
                <label for="user1">Player</label>
                <input type="text"
                       name="user1"
                       style="width: 140px"
                       {% if args["user1"] %}value="{{ args["user1"] }}"{% endif %}
                       placeholder="Username" />
            </p>
            <p class="form_element">
                <label for="deck1">Deck</label>
                <input type="text"
                       name="deck1"
                       {% if args["deck1"] %}value="{{ args["deck1"] }}"{% endif %}
                       placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" />
            </p>
            {{ render_input_number("sas_min1", "SAS >", 33, 108, args.get("sas_min1") ) | safe }}
            {{ render_input_number("sas_max1", "SAS <", 33, 108, args.get("sas_max1") ) | safe }}
            {{ render_input_number("aerc_min1", "AERC >", 33, 108, args.get("aerc_min1") ) | safe }}
            {{ render_input_number("aerc_max1", "AERC <", 33, 108, args.get("aerc_max1") ) | safe }}
        </div>
        <div class="player_filter_inputs">
            <p class="form_element">
                <label for="user2">Player</label>
                <input type="text"
                       name="user2"
                       style="width: 140px"
                       {% if args["user2"] %}value="{{ args["user2"] }}"{% endif %}
                       placeholder="Username" />
            </p>
            <p class="form_element">
                <label for="deck2">Deck</label>
                <input type="text"
                       name="deck2"
                       {% if args["deck2"] %}value="{{ args["deck2"] }}"{% endif %}
                       placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" />
            </p>
            {{ render_input_number("sas_min2", "SAS >", 33, 108, args.get("sas_min2") ) | safe }}
            {{ render_input_number("sas_max2", "SAS <", 33, 108, args.get("sas_max2") ) | safe }}
            {{ render_input_number("aerc_min2", "AERC >", 33, 108, args.get("aerc_min2") ) | safe }}
            {{ render_input_number("aerc_max2", "AERC <", 33, 108, args.get("aerc_max2") ) | safe }}
        </div>
        <label for="sort1">Sort By</label>
        <br />
        {{ render_dropdown('sort1', sort_options, args.get('sort1') ) | safe }}
        <br />
        <label for="direction1">Order</label>
        <br />
        {{ render_dropdown('direction1', {'desc': 'Descending', 'asc': 'Ascending'}, args.get('direction1') ) | safe }}
        <br />
        <button type="submit">Submit</button>
    </form>
    <script type="text/javascript"
            src="{{ url_for("static", filename="js/cleanform.js") }}"></script>
    {% if games %}
        <div class="games_list">
            {% for game in games %}{{ render_game_listing(game) | safe }}{% endfor %}
        </div>
    {% endif %}
{% endblock %}

keytracker/templates/layout.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <title>
            {% block title %}{{ title }}{% endblock %}
        </title>
        <meta charset="utf-8" />
        <meta name="keywords" content="HTML, CSS, JavaScript" />
        <meta name="description" content="{{ description }}" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="{{ url_for('ui.home', _external=True) }}" />
        <meta property="og:title" content="{{ title }}" />
        <meta property="og:description" content="{{ description }}" />
        <meta property="og:image" content="https://ancientbearrepublic.com/abr.png" />
        <link rel="icon"
              type="image/x-icon"
              href="{{ url_for('static', filename='favicon.ico') }}" />
        <link rel="icon"
              type="image/png"
              sizes="32x32"
              href="{{ url_for('static', filename='favicon-32x32.png') }}" />
        <link rel="icon"
              type="image/png"
              sizes="16x16"
              href="{{ url_for('static', filename='favicon-16x16.png') }}" />
        <link rel="apple-touch-icon"
              sizes="180x180"
              href="{{ url_for('static', filename='apple-touch-icon.png') }}" />
        {% block css %}
            <link href="{{ url_for("static", filename="css/style.css") }}"
                  rel="stylesheet" />
        {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    </head>
    <body>
        {% include "navigation.html" %}
        <div class="content">
            {% for message in get_flashed_messages() %}<div class="alert">{{ message }}</div>{% endfor %}
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

keytracker/templates/privacy.html
{% extends "layout.html" %}
{% block content %}
    <div class="introduction">
        <h1>{{ title }}</h1>
        <p>{{ description }}</p>
    </div>
    <div class="privacy_policy">
        <h2>Policy</h2>
        <ul>
            <li>
                Bear Tracks (tracker.ancientbearrepublic.com) is committed to
                sharing as much data about KeyForge online play as possible.
                Bear Tracks may collect and store some other information as well,
                for security and debugging purposes, which has nothing to do with
                the game played. Bear Tracks will not re-distribute that information
                unless for security purposes (and then we would publish an
                explanation), nor sell it for any reason.
            </li>
        </ul>
        <h2>Information collected</h2>
        <ul>
            <li>
                Information we intend to share and analyze as much as possible:
                anything relevant to understanding KeyForge play. Specifically, this
                includes but is not limited to: Usernames, deck ids and card
                content, crucible game id, time played, play decisions made, time
                between decisions, player chat log. We do not intend to sell
                this information, since we are already making it available for free.
                But, we may limit some analytical tools to paid supporters.
            </li>
            <li>
                Information we will not re-distribute or sell: any personal
                identifying information that is not relevant to the game.
                Specifically, this includes IP addresses.
            </li>
        </ul>
        <h2>Use of collected information</h2>
        <ul>
            <li>
                Bear Tracks may use personal information collected on the website and
                any related apps and/or browser extensions for purpose of sharing
                KeyForge game histories, and for analyzing KeyForge decks, cards,
                and strategy.
            </li>
            <li>
                Bear Tracks may modify and/or expunge some data at
                users' request, in order to avoid controversy. Such modifications
                are done entirely at administrators' discretion.
            </li>
            <li>
                Bear Tracks may modify and/or expunge data in bulk if it is
                determined to be, or likely to be, inaccurate. Such modifications
                are done entirely at administrators' discretion.
            </li>
            <li>
                Bear Tracks may use "cookies" in order to deliver content specific
                to users' interest, or to personalize users' experience on the site.
            </li>
        </ul>
        <h2>Distribution of collected information</h2>
        <ul>
            <li>
                Bear Tracks will distribute all game-related information on a
                regular basis via the website, and occasionally via bulk data dumps.
                Those data dumps will be made available for as long as feasible.
            </li>
        </ul>
        <h2>Individual Choice</h2>
        <ul>
            <li>
                Uploading of game information to Bear Tracks is entirely voluntary,
                and submission of data indicates acceptance of this policy.
            </li>
        </ul>
        <h2>
            Someone else uploaded a game they played with me, and I don't like it.
            What can I do about it?
        </h2>
        <ul>
            <li>
                First of all, rights to upload the data are the responsibility of
                the person doing the uploading. In general, we depend on them to
                have obtained logs and other information through appropriate,
                legal means. If we become aware that data was acquired illegally
                or inappropriately, we will remove it.
            </li>
            <li>
                While you do not have an inherent right to edit data someone else has
                acquired via appropriate and legal means, Bear Tracks reserves the
                right to modify data, and will maintain a list of usernames that
                will be replaced with "anonymous" upon upload. Addition to that
                list is not guaranteed, and is contingent upon providing sufficient
                evidence to administrators that you are the person who controls
                that username on thecrucible.online. Upon addition to the list,
                administrators will also modify all existing games in order to
                completely remove the username from our database. Unfortunately,
                this will not affect bulk data dumps that took place prior to
                the username's addition to the list. If you wish to be removed
                from the list in the future, we will make no attempts to
                restore anonymized data. It's a one-way change.
            </li>
        </ul>
    </div>
{% endblock %}

keytracker/templates/profile.html
{% extends "layout.html" %}
{% block content %}Welcome, {{ user.name }}!{% endblock %}

keytracker/templates/upload.html
{% extends "layout.html" %}
{% block content %}
    {% if success %}<div class="success">Successfully uploaded {{ success }}</div>{% endif %}
    <h1>Submit a game log</h1>
    <form method="post">
        <label for="log">Log Text</label>
        <br />
        <textarea type="text"
                  name="log"
                  placeholder=""
                  rows="30"
                  cols="90"
                  value="{{request.form['title'] }}"></textarea>
        <br />
        <button type="submit">Submit</button>
    </form>
{% endblock %}

keytracker/templates/upload_simple.html
{% extends "layout.html" %}
{% block content %}
    {% if success %}<div class="success">Successfully uploaded {{ success }}</div>{% endif %}
    <h1>Submit game data</h1>
    <form method="post">
        <label for="crucible_game_id">Crucible Game ID</label>
        <br />
        <input type="text"
               name="crucible_game_id"
               placeholder="ID from url OR something unique" />
        <br />
        <label for="date">Game Start Time</label>
        <br />
        <input type="datetime-local" name="date" placeholder="" />
        <br />
        <label for="first_player">Who went first?</label>
        <br />
        <select id="first_player" name="first_player">
            <option value="winner">Winner</option>
            <option value="loser">Loser</option>
        </select>
        <br />
        <label for="winner">Winning Player Name</label>
        <br />
        <input type="text" name="winner" placeholder="Player Name" />
        <br />
        <label for="winner_deck_id">Winning Deck ID</label>
        <br />
        <input type="text"
               name="winner_deck_id"
               placeholder="deck_id or whole MV/DoK link" />
        <br />
        <label for="winner_deck_name">Name of Winning Deck</label>
        <br />
        <input type="text"
               name="winner_deck_name"
               placeholder="Please copy/paste or just leave blank" />
        <br />
        <label for="winner_keys">Keys Forged By Winning Player</label>
        <br />
        <input type="number" name="winner_keys" />
        <br />
        <label for="loser">Losing Player Name</label>
        <br />
        <input type="text" name="loser" placeholder="Player Name" />
        <br />
        <label for="loser_deck_id">Losing Deck ID</label>
        <br />
        <input type="text"
               name="loser_deck_id"
               placeholder="deck_id or whole MV/DoK link" />
        <br />
        <label for="loser_deck_name">Name of Losing Deck</label>
        <br />
        <input type="text"
               name="loser_deck_name"
               placeholder="Please copy/paste or just leave blank" />
        <br />
        <label for="loser_keys">Keys Forged By Losing Player</label>
        <br />
        <input type="number" name="loser_keys" />
        <br />
        <button type="submit">Submit</button>
    </form>
{% endblock %}

keytracker/templates/user.html
{% extends "layout.html" %}
{% block content %}
    <div class="user_header">
        <h1>Record of games for {{ username }}</h1>
        <div class="games_summary">
            Total games played: {{ games_won + games_lost }} | Games won: {{ games_won }}
            ( {{ '%0.2f' | format(games_won / ( games_won + games_lost) * 100) }}% )
        </div>
    </div>
    <div class="games_list">
        {% for game in games %}{{ render_game_listing(game, username=username) | safe }}{% endfor %}
    </div>
{% endblock %}